@TestServer_HostAddress = http://localhost:5000
@ApiKey = replace-with-your-api-key

POST {{TestServer_HostAddress}}/api/message
Content-Type: application/json
X-API-Key: {{ApiKey}}

{
  "message": "Ping"
}

###

POST {{TestServer_HostAddress}}/api/message
Content-Type: application/json
X-API-Key: {{ApiKey}}

{
  "message": "Server info"
}

### Requires Shutdown:Enabled=true and sufficient OS privileges

POST {{TestServer_HostAddress}}/api/message
Content-Type: application/json
X-API-Key: {{ApiKey}}

{
  "message": "Shutdown Linux machine"
}
